"use client";

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'ES' | 'EN';

type LanguageContextType = {
  language: Language;
  toggleLanguage: () => void;
  t: (key: string) => string;
};

const translations = {
  ES: {
    'nav.search': 'Descubre tu próxima suscripción...',
    'nav.catalog': 'Catálogo',
    'nav.about': 'Sobre Mí',
    'nav.support': 'Soporte',
    'nav.login': 'Entrar',
    'nav.dashboard': 'Mi Panel',
    'hero.title': 'Ahorra hasta 85% en IA, streaming y juegos premium.',
    'hero.desc': 'Inauguramos nuestra nueva tienda web con el respaldo de 5 años de experiencia vendiendo cuentas premium de streaming y juegos. Compra con total seguridad y recibe acceso inmediato.',
    'cat.all': 'Todo',
    'cat.streaming': 'Streaming',
    'cat.ai': 'IA',
    'cat.music': 'Música',
    'cat.games': 'Juegos',
    'cat.recharges': 'Diamantes de Free Fire',
    'empty.search': 'No se encontraron productos para tu búsqueda.',
    'why.title': '¿Por qué elegirnos?',
    'why.exp.title': '5 Años de Experiencia',
    'why.exp.desc': 'Hemos brindado servicio a miles de clientes a través de redes sociales, ahora con tienda web oficial.',
    'why.delivery.title': 'Entrega Inmediata',
    'why.delivery.desc': 'Recibe tu cuenta y credenciales automáticamente tras tu pago.',
    'why.warranty.title': 'Garantía Total',
    'why.warranty.desc': 'Cuentas 100% legales y garantizadas durante todo tu periodo.',
    'why.support.title': 'Soporte Dedicado',
    'why.support.desc': 'Atención personalizada para resolver cualquier inconveniente rápidamente.',
    'about.title': 'Sobre Mí',
    'about.subtitle': 'De las redes a tu pantalla',
    'about.desc1': '¡Hola! Soy Diego, y durante los últimos 5 años me he dedicado a acercar el mejor entretenimiento digital a miles de personas.',
    'about.desc2': 'Lo que empezó como ventas a través de redes, hoy evoluciona en esta plataforma oficial para brindarte mayor seguridad y comodidad. Mi compromiso sigue siendo el mismo: cuentas legales, precios accesibles y garantía total.',
    'ref.title': 'Referencias de Clientes Reales',
    'cart.add': 'Agregar al Carrito',
    'cart.title': 'Tu Carrito',
    'cart.empty': 'Tu carrito está vacío',
    'cart.subtotal': 'Subtotal',
    'cart.checkout.card': 'Pagar con Tarjeta',
    'cart.checkout.paypal': 'Pagar con PayPal',
    'modal.includes': '¿Qué incluye?',
    'product.month': '/ mes',
    'product.details': 'Ver más detalles',
    'product.stock.available': 'cuentas disponibles',
    'product.stock.out': 'Agotado',
    'product.stock.none': 'Sin Stock',
    'dashboard.purchases': 'Mis Compras',
    'dashboard.purchases.empty': 'Aún no tienes suscripciones activas. ¡Explora el catálogo!',
    'dashboard.admin': 'Panel de Administrador',
    'dashboard.logout': 'Cerrar Sesión',
    'footer.desc': 'Tu tienda de confianza para servicios digitales premium.',
    'footer.links': 'Enlaces',
    'footer.legal': 'Legales',
    'footer.terms': 'Términos y Condiciones',
    'footer.privacy': 'Política de Privacidad',
    'footer.rights': 'Todos los derechos reservados.',
    'footer.developed': 'Desarrollado por',
    'review.title': 'Opiniones de nuestros clientes',
    'review.leave': 'Dejar una opinión',
    'review.name': 'Tu nombre',
    'review.comment': 'Cuéntanos tu experiencia...',
    'review.submit': 'Publicar Opinión',
    'review.empty': 'Aún no hay opiniones. ¡Sé el primero en comentar!',
    'product.verify_id': 'Chat para recargar',
    'product.recharge.available': 'Disponible para Recarga',
    'product.recharge.request': 'Solicitar Recarga',
    'chat.title': 'Chat de Soporte',
    'chat.placeholder': 'Escribe tu mensaje...',
    'chat.send': 'Enviar',
    'chat.admin_title': 'Admin',
    'chat.user_title': 'Tú',
    'admin.chats.active': 'Chats Activos',
    'admin.chats.loading': 'Cargando chats...',
    'admin.chats.empty': 'No tienes chats activos.',
    'admin.chats.click_to_view': 'Clic para ver chat',
    'admin.chats.close_chat': 'Cerrar Chat',
    'admin.chats.delete_title': '¿Eliminar Chat?',
    'admin.chats.delete_desc': 'Esta acción no se puede deshacer.',
    'admin.chats.delete_cancel': 'Cancelar',
    'admin.chats.delete_confirm': 'Eliminar',
    'admin.chats.status_open': 'Abierto',
    'admin.chats.status_closed': 'Cerrado',
    'chat.support.name': 'Atención al Cliente',
    'chat.loading': 'Cargando...',
    'chat.welcome': '👋 ¡Hola! Soy el asistente de soporte. ¿En qué te puedo ayudar hoy?',
    'chat.quick.payment': 'Problema de pago',
    'chat.quick.account': 'Ayuda con cuenta',
    'chat.quick.other': 'Otra consulta',
    'chat.quick.ask_id': 'Pedir ID',
    'chat.quick.id_verified': 'ID Verificado',
    'chat.quick.processing': 'Procesando',
    'chat.quick.completed': 'Completada',
    'chat.btn.payment': '💰 Botón Pago',
    'chat.payment.approved': 'Recarga Aprobada',
    'chat.payment.pay_card': '💳 Pagar con Tarjeta',
    'chat.payment.processing': 'Procesando...',
    'chat.payment.error': 'Error. Intentar de nuevo',
    'widget.theme': 'Cambiar Tema',
    'widget.admin': 'Panel Admin',
    'widget.support': 'Soporte',
    'cart.checkout.finalize': 'Finalizar Compra',
    'checkout.title': 'Pago Seguro',
    'checkout.total': 'Total a pagar',
    'checkout.email': 'Correo electrónico para entrega',
    'checkout.email.placeholder': 'tu@correo.com',
    'checkout.method': 'Método de pago',
    'checkout.card': 'Tarjeta',
    'checkout.card.number': 'Número de Tarjeta',
    'checkout.card.expiry': 'Vencimiento',
    'checkout.card.cvv': 'CVV',
    'checkout.pay_btn': 'Pagar',
    'checkout.secure': 'Pagos encriptados de forma segura',
    'checkout.processing.title': 'Procesando pago...',
    'checkout.processing.desc': 'Por favor no cierres esta ventana',
    'checkout.success.title': '¡Pago Exitoso!',
    'checkout.success.desc': 'Tu compra se ha procesado correctamente. Te estamos redirigiendo a tu Dashboard donde podrás ver tus cuentas.',
    'checkout.error': 'Error al procesar el pago',
    'catalog.loading': 'Cargando productos...',
    'catalog.load_more': 'Ver más',
    'dashboard.order.verifying': 'Verificando Pago',
    'dashboard.order.active': 'Activa',
    'dashboard.order.verifying_desc1': 'Tu comprobante de transferencia está siendo verificado.',
    'dashboard.order.verifying_desc2': 'Tus credenciales aparecerán aquí pronto.',
    'dashboard.order.user': 'Usuario:',
    'dashboard.order.password': 'Contraseña:',
    'dashboard.order.profile': 'Perfil/PIN:',
    'dashboard.order.bought_on': 'Comprado el',
    'dashboard.order.renew': 'Renovar',
    'admin.tab.products': 'Productos',
    'admin.tab.reviews': 'Opiniones',
    'admin.tab.chats': 'Chats',
    'admin.tab.orders': 'Transferencias',
    'admin.prod.add_title': 'Añadir Nuevo Producto',
    'admin.prod.name': 'Nombre del Producto',
    'admin.prod.name_placeholder': 'Ej: Cuenta de Free Fire',
    'admin.prod.desc': 'Descripción',
    'admin.prod.desc_placeholder': 'Detalles de la cuenta o producto... (Máx 400 caracteres)',
    'admin.prod.price': 'Precio (USD)',
    'admin.prod.category': 'Categoría',
    'cat.ai_full': 'Inteligencia Artificial',
    'cat.games_full': 'Juegos (Gral)',
    'admin.prod.stock': 'Stock Inicial / Cuentas (Opcional)',
    'admin.prod.email_ph': 'Correo de la cuenta...',
    'admin.prod.pass_ph': 'Contraseña...',
    'admin.prod.add_btn': '+ Añadir',
    'admin.prod.bulk': 'O pegar lista masiva (correo:contraseña)',
    'admin.prod.color': 'Color de Fondo',
    'admin.prod.color_desc': 'El icono se generará automáticamente.',
    'admin.prod.image': 'Imagen (Opcional)',
    'admin.prod.image_file': 'Archivo seleccionado (Ignorando URL)',
    'admin.prod.image_url': 'Pegar URL externa...',
    'admin.prod.saving': 'Guardando...',
    'admin.prod.save': 'Guardar Producto',
  },
  EN: {
    'nav.search': 'Discover your next subscription...',
    'nav.catalog': 'Catalog',
    'nav.about': 'About Me',
    'nav.support': 'Support',
    'nav.login': 'Login',
    'nav.dashboard': 'My Dashboard',
    'hero.title': 'Save up to 85% on premium AI, streaming, and gaming.',
    'hero.desc': 'Opening our new web store backed by 5 years of experience selling premium streaming and gaming accounts. Shop securely and get instant access.',
    'cat.all': 'All',
    'cat.streaming': 'Streaming',
    'cat.ai': 'AI',
    'cat.music': 'Music',
    'cat.games': 'Games',
    'cat.recharges': 'Free Fire Diamonds',
    'empty.search': 'No products found for your search.',
    'why.title': 'Why Choose Us?',
    'why.exp.title': '5 Years of Experience',
    'why.exp.desc': 'We have served thousands of customers through social media, now with an official web store.',
    'why.delivery.title': 'Instant Delivery',
    'why.delivery.desc': 'Receive your account and credentials automatically after payment.',
    'why.warranty.title': 'Total Warranty',
    'why.warranty.desc': '100% legal accounts guaranteed throughout your subscription period.',
    'why.support.title': 'Dedicated Support',
    'why.support.desc': 'Personalized attention to resolve any issues quickly.',
    'about.title': 'About Me',
    'about.subtitle': 'From social media to your screen',
    'about.desc1': 'Hello! I am Diego, and for the past 5 years I have dedicated myself to bringing the best digital entertainment to thousands of people.',
    'about.desc2': 'What started as sales through social networks, today evolves into this official platform to provide greater security and comfort. My commitment remains the same: legal accounts, affordable prices, and total warranty.',
    'ref.title': 'Real Customer References',
    'cart.add': 'Add to Cart',
    'cart.title': 'Your Cart',
    'cart.empty': 'Your cart is empty',
    'cart.subtotal': 'Subtotal',
    'cart.checkout.card': 'Pay with Card',
    'cart.checkout.paypal': 'Pay with PayPal',
    'modal.includes': 'What is included?',
    'product.month': '/ month',
    'product.details': 'View details',
    'product.stock.available': 'accounts available',
    'product.stock.out': 'Out of Stock',
    'product.stock.none': 'No Stock',
    'dashboard.purchases': 'My Purchases',
    'dashboard.purchases.empty': 'You have no active subscriptions yet. Explore our catalog!',
    'dashboard.admin': 'Admin Dashboard',
    'dashboard.logout': 'Logout',
    'footer.desc': 'Your trusted store for premium digital services.',
    'footer.links': 'Links',
    'footer.legal': 'Legal',
    'footer.terms': 'Terms & Conditions',
    'footer.privacy': 'Privacy Policy',
    'footer.rights': 'All rights reserved.',
    'footer.developed': 'Developed by',
    'review.title': 'Customer Reviews',
    'review.leave': 'Leave a review',
    'review.name': 'Your name',
    'review.comment': 'Tell us about your experience...',
    'review.submit': 'Post Review',
    'review.empty': 'No reviews yet. Be the first to comment!',
    'product.verify_id': 'Chat to Recharge',
    'product.recharge.available': 'Available for Recharge',
    'product.recharge.request': 'Request Recharge',
    'chat.title': 'Support Chat',
    'chat.placeholder': 'Type your message...',
    'chat.send': 'Send',
    'chat.admin_title': 'Admin',
    'chat.user_title': 'You',
    'admin.chats.active': 'Active Chats',
    'admin.chats.loading': 'Loading chats...',
    'admin.chats.empty': 'You have no active chats.',
    'admin.chats.click_to_view': 'Click to view chat',
    'admin.chats.close_chat': 'Close Chat',
    'admin.chats.delete_title': 'Delete Chat?',
    'admin.chats.delete_desc': 'This action cannot be undone.',
    'admin.chats.delete_cancel': 'Cancel',
    'admin.chats.delete_confirm': 'Delete',
    'admin.chats.status_open': 'Open',
    'admin.chats.status_closed': 'Closed',
    'chat.support.name': 'Customer Support',
    'chat.loading': 'Loading...',
    'chat.welcome': '👋 Hello! I am the support assistant. How can I help you today?',
    'chat.quick.payment': 'Payment issue',
    'chat.quick.account': 'Account help',
    'chat.quick.other': 'Other inquiry',
    'chat.quick.ask_id': 'Ask for ID',
    'chat.quick.id_verified': 'ID Verified',
    'chat.quick.processing': 'Processing',
    'chat.quick.completed': 'Completed',
    'chat.btn.payment': '💰 Payment Button',
    'chat.payment.approved': 'Recharge Approved',
    'chat.payment.pay_card': '💳 Pay with Card',
    'chat.payment.processing': 'Processing...',
    'chat.payment.error': 'Error. Try again',
    'widget.theme': 'Toggle Theme',
    'widget.admin': 'Admin Panel',
    'widget.support': 'Support',
    'cart.checkout.finalize': 'Checkout',
    'checkout.title': 'Secure Payment',
    'checkout.total': 'Total to pay',
    'checkout.email': 'Delivery email address',
    'checkout.email.placeholder': 'you@email.com',
    'checkout.method': 'Payment method',
    'checkout.card': 'Card',
    'checkout.card.number': 'Card Number',
    'checkout.card.expiry': 'Expiry',
    'checkout.card.cvv': 'CVV',
    'checkout.pay_btn': 'Pay',
    'checkout.secure': 'Payments securely encrypted',
    'checkout.processing.title': 'Processing payment...',
    'checkout.processing.desc': 'Please do not close this window',
    'checkout.success.title': 'Payment Successful!',
    'checkout.success.desc': 'Your purchase was processed successfully. You are being redirected to your Dashboard to view your accounts.',
    'checkout.error': 'Error processing payment',
    'catalog.loading': 'Loading products...',
    'catalog.load_more': 'See more',
    'dashboard.order.verifying': 'Verifying Payment',
    'dashboard.order.active': 'Active',
    'dashboard.order.verifying_desc1': 'Your transfer receipt is being verified.',
    'dashboard.order.verifying_desc2': 'Your credentials will appear here soon.',
    'dashboard.order.user': 'User:',
    'dashboard.order.password': 'Password:',
    'dashboard.order.profile': 'Profile/PIN:',
    'dashboard.order.bought_on': 'Purchased on',
    'dashboard.order.renew': 'Renew',
    'admin.tab.products': 'Products',
    'admin.tab.reviews': 'Reviews',
    'admin.tab.chats': 'Chats',
    'admin.tab.orders': 'Transfers',
    'admin.prod.add_title': 'Add New Product',
    'admin.prod.name': 'Product Name',
    'admin.prod.name_placeholder': 'Ex: Free Fire Account',
    'admin.prod.desc': 'Description',
    'admin.prod.desc_placeholder': 'Account or product details... (Max 400 chars)',
    'admin.prod.price': 'Price (USD)',
    'admin.prod.category': 'Category',
    'cat.ai_full': 'Artificial Intelligence',
    'cat.games_full': 'Games (General)',
    'admin.prod.stock': 'Initial Stock / Accounts (Optional)',
    'admin.prod.email_ph': 'Account email...',
    'admin.prod.pass_ph': 'Password...',
    'admin.prod.add_btn': '+ Add',
    'admin.prod.bulk': 'Or paste bulk list (email:password)',
    'admin.prod.color': 'Background Color',
    'admin.prod.color_desc': 'Icon will be generated automatically.',
    'admin.prod.image': 'Image (Optional)',
    'admin.prod.image_file': 'File selected (Ignoring URL)',
    'admin.prod.image_url': 'Paste external URL...',
    'admin.prod.saving': 'Saving...',
    'admin.prod.save': 'Save Product',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('ES');

  useEffect(() => {
    const savedLang = localStorage.getItem('lang') as Language;
    if (savedLang && (savedLang === 'ES' || savedLang === 'EN')) {
      setLanguage(savedLang);
    }
  }, []);

  const toggleLanguage = () => {
    setLanguage(prev => {
      const newLang = prev === 'ES' ? 'EN' : 'ES';
      localStorage.setItem('lang', newLang);
      return newLang;
    });
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['ES']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
